### ISSUE TITLE
About NeuRAD-L

### ISSUE THREAD

**Issue by szhang963** [atonderski/neuro-ncap#1]
Hi, I am very interested in the great work. 

However, I have some questions about the part of the neural render. I claim the reconstruction quality can be improved by a larger configuration (NeuRAD-L). I‘d like to understand what changes have been made for the larger configuration? 

Could you provide some information about this?
Thanks in advance.

**Comment by atonderski** [comment]
You can now find more details in the latest arxiv version :)
https://arxiv.org/abs/2311.15260
